name: camera_app

description: "A Flutter skin care analysis app with camera functionality."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted to a broader range for better compatibility

dependencies:
  flutter:
    sdk: flutter

  # Existing
  camera: ^0.10.5
  image: ^4.5.3
  google_mlkit_face_detection: ^0.11.0
  google_fonts: ^6.2.0
  http: ^1.1.0
  image_picker: ^1.0.7
  fl_chart: ^0.68.0

  # New - Authentication & Database
  supabase_flutter: ^2.5.0
  shared_preferences: ^2.2.3

  # New - UI Components
  smooth_page_indicator: ^1.1.0
  intl: ^0.19.0




dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"


flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/haarcascade_frontalface_default.xml
    - Assets/face.png # Added for the avatar image referenced in your dashboard
    - Assets/product.png
    - assets/icon/
    - assets/images/splash.png

  # Optional: Add custom fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf